### ISSUE TITLE
[Bug] Loading indicators UI bug

### ISSUE THREAD

**Issue by SimChadha** [sandboxnu/ScoutTrek-Frontend#33]
**Summary:** Loading indicators appear off screen or in otherwise strange places.

**Expected:** Loading indicators are center on the screen
**Actual:** Loading indicators appear in the top left of the screen on the calendar page and aren't visible on the profile screen (could be rendering in the iPhone 14 island in the video)

**To-do:**
- [ ] Make loading indicators consistent in their position
- [ ] Loading indicators are the same across all screens
    - [ ] The profile screen may use a loading wheel while the other two screens just use some text. If so, use the loading wheel everywhere

https://user-images.githubusercontent.com/54784088/215357483-11b00b0e-2525-40b2-b710-4910637903ca.mov
