### ISSUE TITLE
Profile Picture upload

### ISSUE THREAD

**Issue by SimChadha** [sandboxnu/ScoutTrek-Frontend#40]
Add functionality for adding profile pictures on the profile screen. As of now, uploading an image bugs out and gets rid of the icon. 

## Todo:
- [ ] User can upload a photo from their device
- [ ] Photo is saved to our servers for the user
- [ ] Preview is updated to the new photo
