### ISSUE TITLE
Allow user RSVP for events (Milestone 1 part 1)

### ISSUE THREAD

**Issue by SimChadha** [sandboxnu/ScoutTrek-Frontend#48]
Users should have an option for an event to RSVP as a yes, no, or maybe. Follow the designs [here](https://www.figma.com/file/ay7xX8FXxdR03bwBOYv6vX/ScoutTrek?node-id=244%3A445&t=5pF5RCZ8HVChJRj9-0) on the Event Roster page under "Invitee View". This data should then be stored in the backend for the event.

- [x] Menu with 3 RSVP options is on event screen
- [x] User can select an option and their changes are reflected in the UI (button is highlighted)
- [x] Choice is reflected in event data
